import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Feed from '@/components/User/Feed/Feed'
import Sidebar from '@/components/User/Layouts/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Seeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        {/* sidebar */}
    
        <Sidebar />
        {/* feed */}
        <Feed />

        
        {/* widgets */}

        {/* modal */}
      </main>
      
     
    </>
  )
}
